POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7,
  "id": "68f53c023552e5958a628150"
}
###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5,
  "id": "68f53c023552e5958a628151"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": 12,
  "id": "68f53c023552e5958a628152"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
  "likes": 10,
  "id": "68f53c023552e5958a628153"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
  "id": "68f53c023552e5958a628154"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2,
  "id": "68f53c023552e5958a628155"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "my first blog",
  "author": "teemu teekkari",
  "url": "www.teemuteekkari/myfirstblog",
  "likes": 0,
  "user": "68f53fdb5d8bf8025ff91986",
  "id": "68f54319af6d8388df9478fd"
}